version: '3.2'
services:
#  app:
#    image: 'dac-delivery-api/app:1'
#    build: ./app
#    container_name: app
#    ports:
#      - "8081:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dac-delivery-db
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    container_name: database
    image: 'dac-jsf/database:1'
    build: ./docker/postgres
    ports:
      - "5433:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata:
    driver: local
